apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emcip-tdlib-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emcip.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.tdlibDb.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emcip-tdlib-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emcip.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.tdlibFiles.size }}
