apiVersion: v1
kind: Service
metadata:
  name: emcip-tdlib-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emcip.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tdlibAdapter.port }}
      targetPort: {{ .Values.tdlibAdapter.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.tdlibAdapter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
