apiVersion: v1
kind: ConfigMap
metadata:
  name: emcip-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emcip.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://emcip-loki:3100
        isDefault: true
        version: 1
        editable: false
