apiVersion: v1
kind: Service
metadata:
  name: emcip-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emcip.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.infra.prometheus.port }}
      targetPort: {{ .Values.infra.prometheus.port }}
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
