server:
  port: 9086

spring:
  application:
    name: emcip-audit-service
  r2dbc:
    url: r2dbc:postgresql://localhost:14005/emcip
    username: emcip
    password: emcip
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    io.emcip: INFO
