export const ROLE_PERMISSIONS = {
  ADMIN: [
    'GROUPS_READ', 'GROUPS_WRITE',
    'POLICY_RULES_READ', 'POLICY_RULES_WRITE',
    'MODERATION_RULES_READ', 'MODERATION_RULES_WRITE',
    'AUDIT_READ',
    'TELEGRAM_READ', 'TELEGRAM_WRITE',
    'SIMULATE_WRITE',
    'AI_CONFIG_READ', 'AI_CONFIG_WRITE',
    'TENANTS_READ', 'TENANTS_WRITE',
    'USERS_READ', 'USERS_WRITE',
  ],
  TENANT_ADMIN: [
    'GROUPS_READ', 'GROUPS_WRITE',
    'POLICY_RULES_READ', 'POLICY_RULES_WRITE',
    'MODERATION_RULES_READ', 'MODERATION_RULES_WRITE',
    'AUDIT_READ',
    'TELEGRAM_READ', 'TELEGRAM_WRITE',
    'SIMULATE_WRITE',
  ],
}

export function hasPermission(role, permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false
}
