export const ROLE_PERMISSIONS = {
  ADMIN: [
    'GROUPS_READ', 'GROUPS_WRITE',
    'POLICY_RULES_READ', 'POLICY_RULES_WRITE',
    'MODERATION_RULES_READ', 'MODERATION_RULES_WRITE',
    'AUDIT_READ',
    'TELEGRAM_READ', 'TELEGRAM_WRITE',
    'SIMULATE_WRITE',
    'AI_CONFIG_READ', 'AI_CONFIG_WRITE',
    'COSTS_READ',
    'TENANTS_READ', 'TENANTS_WRITE',
    'USERS_READ', 'USERS_WRITE',
    'RESOLUTION_REVIEW_READ', 'RESOLUTION_REVIEW_WRITE',
    'KNOWLEDGE_READ', 'KNOWLEDGE_WRITE',
    'INTEGRATIONS_GLOBAL_MANAGE',
    'INTEGRATIONS_TENANT_MANAGE',
  ],
  TENANT_ADMIN: [
    'GROUPS_READ', 'GROUPS_WRITE',
    'POLICY_RULES_READ', 'POLICY_RULES_WRITE',
    'MODERATION_RULES_READ', 'MODERATION_RULES_WRITE',
    'AUDIT_READ',
    'TELEGRAM_READ', 'TELEGRAM_WRITE',
    'SIMULATE_WRITE',
    'COSTS_READ',
    'RESOLUTION_REVIEW_READ', 'RESOLUTION_REVIEW_WRITE',
    'KNOWLEDGE_READ', 'KNOWLEDGE_WRITE',
    'INTEGRATIONS_TENANT_MANAGE',
  ],
  MODERATOR: [
    'GROUPS_READ', 'GROUPS_WRITE',
    'POLICY_RULES_READ', 'POLICY_RULES_WRITE',
    'MODERATION_RULES_READ', 'MODERATION_RULES_WRITE',
    'AUDIT_READ',
    'TELEGRAM_READ',
    'SIMULATE_WRITE',
    'RESOLUTION_REVIEW_READ', 'RESOLUTION_REVIEW_WRITE',
    'KNOWLEDGE_READ',
  ],
  ANALYST: [
    'GROUPS_READ',
    'POLICY_RULES_READ',
    'MODERATION_RULES_READ',
    'AUDIT_READ',
    'TELEGRAM_READ',
    'COSTS_READ',
    'RESOLUTION_REVIEW_READ',
    'KNOWLEDGE_READ',
  ],
  VIEWER: [
    'GROUPS_READ',
    'AUDIT_READ',
    'TELEGRAM_READ',
  ],
}

export function hasPermission(role, permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false
}
