server:
  port: 14009

spring:
  application:
    name: emcip-admin-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
